// src/worksData.js
export const works = [
  {
    id: 1,
    title: "Hungry Bob Korean Fusion",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=11KlL7MA63VUUZ1UE62IyEcpjl4vhlU9-&sz=w2000",
  },
  {
    id: 2,
    title: "Dabang Coffee",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1Fz3WRHRAnEASv8o9weSl9zkaABeHPOcl&sz=w2000",
  },
  {
    id: 3,
    title: "OnePiece Resto Café",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=1Ls03GqEQlzR79_x2uMCNpufpR49jWidy&sz=w2000",
  },
  {
    id: 4,
    title: "Pugad ni Art Studio",
    tag: "pugad",
    desc: "Wall design • creative mural paintings",
    img: "https://drive.google.com/thumbnail?id=1P0jAIG7HfAgbg2fF_ud4cfd7PX5MUjYq&sz=w2000",
  },
  {
    id: 5,
    title: "Oswald (Music Artist)",
    tag: "oswald",
    desc: "Music video editing • thumbnail • Spotify artwork • teaser reels",
    img: "https://drive.google.com/thumbnail?id=1K40wkYyfykHTEcaFj9HiuWW1CBDOeaJc&sz=w2000",
    type: "video",
    video:
      "https://drive.google.com/file/d/1aoO6sOTXgEl0rnIXV8R2zzEmitSlK_bY/view?usp=drive_link",
  },
  {
    id: 6,
    title: "Café Will Restaurant",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1tztO7K6G5MXM1AXi9SUlrVLdQbf27m0T&sz=w2000",
  },
  {
    id: 7,
    title: "Café Will Restaurant Image 1",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1V4TjVzDcA4zZBWNRPNxTgrt85rcUvgVp&sz=w2000",
  },
  {
    id: 8,
    title: "Café Will Restaurant Image 2",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1i8Ivv08VAwT2F9GmaOg117pFkno00nqe&sz=w2000",
  },
  {
    id: 9,
    title: "Café Will Restaurant Image 3",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1uBu9oeoKfZb_XF0OJt-Gj-KSycEH7RUW&sz=w2000",
  },
  {
    id: 10,
    title: "Café Will Restaurant Image 4",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=18PfMD2vxN7TNR9YeIXjmwozY45d6XEtx&sz=w2000",
  },
  {
    id: 11,
    title: "Café Will Restaurant Image 5",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1IGcIFdQkzQt7u_P2hP0uN-AdB6b2C7gh&sz=w2000",
  },
  {
    id: 12,
    title: "Café Will Restaurant Image 6",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1aGylqLCOo0RpEnfSjAzleon59u201_un&sz=w2000",
  },
  {
    id: 13,
    title: "Café Will Restaurant Image 7",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=142-wBgRwuBkvhiXd9vMpRydy9KZOnoOI&sz=w2000",
  },
  {
    id: 14,
    title: "Café Will Restaurant Image 8",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1oKqmxytmaS8b-Xrgj6YN2v5QNdnWWXOU&sz=w2000",
  },
  {
    id: 15,
    title: "Café Will Restaurant Image 9",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1XwbzGNtJ-OPDLa-YPezZzvQECnTFapdF&sz=w2000",
  },
  {
    id: 16,
    title: "Café Will Restaurant Image 10",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1KjNqKjwuZfCmAuXOwtd_-h9SMpezMEMR&sz=w2000",
  },
  {
    id: 17,
    title: "Café Will Restaurant Image 11",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1sSUBa9S6f2E8JGf3p58448QhuwlHskYA&sz=w2000",
  },
  {
    id: 18,
    title: "Café Will Restaurant Image 12",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1FZJEFGErw-An1cH1Doszj-452THBpxDW&sz=w2000",
  },
  {
    id: 19,
    title: "Café Will Restaurant Image 13",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1iaedOWaXlOlhgffX6o4oJN2rvk8wqUDF&sz=w2000",
  },
  {
    id: 20,
    title: "Café Will Restaurant Image 14",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1fE-ZzkWknNxL75RGTSmPDUkOFUiI24JT&sz=w2000",
  },
  {
    id: 21,
    title: "Café Will Restaurant Image 15",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1h5BPkISuYmrWM587qln1ATgNKOadlpcr&sz=w2000",
  },
  {
    id: 22,
    title: "Café Will Restaurant Image 16",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1FWlkuiFmhkIll8IDVgbn5uEwq8Bi7Krf&sz=w2000",
  },
  {
    id: 23,
    title: "Café Will Restaurant Image 17",
    tag: "cafe_will",
    desc: "Logo enhancement • printable menus • menu photography",
    img: "https://drive.google.com/thumbnail?id=1LCoPpRJQ-7e80EwstQcAodFGSF41b-BN&sz=w2000",
  },
  {
    id: 24,
    title: "Point Club 1",
    tag: "point_club",
    desc: "Video editing • Graphic Design • Social Media Work • Brochure",
    img: "https://drive.google.com/thumbnail?id=1b2LzjWI4XJ6-4N8WfOldrjLDsx1c8EwM&sz=w2000",
  },
  {
    id: 25,
    title: "Point Club 2",
    tag: "point_club",
    desc: "Video editing • Graphic Design • Social Media Work • Brochure",
    img: "https://drive.google.com/thumbnail?id=1jpwqBgP54Kq_N04AdQ-0UxeScrCB7EGp&sz=w2000",
  },
  {
    id: 26,
    title: "Point Club 3",
    tag: "point_club",
    desc: "Video editing • Graphic Design • Social Media Work • Brochure",
    img: "https://drive.google.com/thumbnail?id=1vc8XUBhhPiZMMO2WiF5gMT5hpezV2am4&sz=w2000",
  },
  {
    id: 27,
    title: "Point Club 5",
    tag: "point_club",
    desc: "Video editing • Graphic Design • Social Media Work • Brochure",
    img: "https://drive.google.com/thumbnail?id=1c0ImuhfLAwT-mBBVC-tLGiETATAyjfW0&sz=w2000",
  },
  {
    id: 28,
    title: "Point Club 7",
    tag: "point_club",
    desc: "Video editing • Graphic Design • Social Media Work • Brochure",
    img: "https://drive.google.com/thumbnail?id=1FXL7hMwarH7OpLJuF0OsX5028s2c9j21&sz=w2000",
  },
  {
    id: 29,
    title: "Point Club 8",
    tag: "point_club",
    desc: "Video editing • Graphic Design • Social Media Work • Brochure",
    type: "video",
    video:
      "https://drive.google.com/file/d/1kgoIw7kV6TkxRPBAlZB4OasV3Y5zfzJi/view?usp=drive_link",
    img: "",
  },
  {
    id: 30,
    title: "Point Club 9",
    tag: "point_club",
    desc: "Video editing • Graphic Design • Social Media Work • Brochure",
    type: "video",
    video:
      "https://drive.google.com/file/d/1d26TB85KGyYZ25M2UJ90DdFfDVgqrnYE/view?usp=drive_link",
    img: "",
  },
  {
    id: 31,
    title: "Point Club 10",
    tag: "point_club",
    desc: "Video editing • Graphic Design • Social Media Work • Brochure",
    img: "https://drive.google.com/thumbnail?id=1iXJVkk6g2Zn-f8eTOTwku-df8EAgv4BG&sz=w2000",
  },
  {
    id: 32,
    title: "Point Club 11",
    tag: "point_club",
    desc: "Video editing • Graphic Design • Social Media Work • Brochure",
    type: "video",
    video:
      "https://drive.google.com/file/d/1S-sbM_p-BYEqiPMGk73Q5U2t_imb-2Cs/view?usp=drive_link",
    img: "",
  },
  {
    id: 33,
    title: "Point Club 12",
    tag: "point_club",
    desc: "Video editing • Graphic Design • Social Media Work • Brochure",
    type: "video",
    video:
      "https://drive.google.com/file/d/1Z9uQLVYDBH73h_Vv_8g4cl50Hr0ezJnv/view?usp=drive_link",
    img: "",
  },
  {
    id: 34,
    title: "Photography 1",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1QtI3Ziho4pZcBHHLW-CqJ6GLVK1y04Zq&sz=w2000",
  },
  {
    id: 35,
    title: "Photography 2",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=13M67-0dCbcZcdqWlhSiQvXZ4x5cIDvHJ&sz=w2000",
  },
  {
    id: 36,
    title: "Photography 3",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1YhSBSu4neJ9_IMqATRszf1owEm0vRI-v&sz=w2000",
  },
  {
    id: 37,
    title: "Photography 4",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1xNbE6J8Uo0NFgVauiNIWa6iWdE269ClG&sz=w2000",
  },
  {
    id: 38,
    title: "Photography 5",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1SkVHc29owp8Ky2Qap6Z55gvsCTdyjD0R&sz=w2000",
  },
  {
    id: 39,
    title: "Photography 6",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1hrqaGSEms6NI3mkmRKEmFmHp2TJ6-WDD&sz=w2000",
  },
  {
    id: 40,
    title: "Photography 7",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1yIP4j4TRrUqCSUo5VWdwjX8JJiZAq04Q&sz=w2000",
  },
  {
    id: 41,
    title: "Photography 8",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1D_-FfOLPpQ6PT_DoLRD_luryAla8mBHc&sz=w2000",
  },
  {
    id: 42,
    title: "Photography 9",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=172Lfu86eT7Yjcs4XXWuYnHbUYOzTtgDP&sz=w2000",
  },
  {
    id: 43,
    title: "Photography 10",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1l-JvHrnnXy_wkDc7Q1Mn7Hh3sazNbg6f&sz=w2000",
  },
  {
    id: 44,
    title: "Photography 11",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1lpO99Oga9lLDjlJy8gSwWSW4wNKhRWEo&sz=w2000",
  },
  {
    id: 45,
    title: "Photography 12",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1VrPq1BcIgBZaTg3Ddrr6FY_voh3CzzRy&sz=w2000",
  },
  {
    id: 46,
    title: "Photography 13",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1DwY6zlTRi1iPQipR-qwgEWKTlP-wuC63&sz=w2000",
  },
  {
    id: 47,
    title: "Photography 14",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1wyFQBxy7SWdE0CoBZ3lzLYULBlaa_DhL&sz=w2000",
  },
  {
    id: 48,
    title: "Photography 15",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1r2c5yZPyoLn6h7hZO5gwq-YhShxDjYY4&sz=w2000",
  },
  {
    id: 49,
    title: "Photography 16",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1NUpO-KEvy7xFH3DGFPRTMs5n_mH2n6Zk&sz=w2000",
  },
  {
    id: 50,
    title: "Photography 17",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1xUt1sFX5eJWt52h_7zaTtWPLfCw0p8ad&sz=w2000",
  },
  {
    id: 51,
    title: "Photography 18",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1Vc5U3gdomE_CxXFVuhC2qOmQPs6hqDTz&sz=w2000",
  },
  {
    id: 52,
    title: "Photography 19",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1wRaC1sRXcm2tfme60LbetbsVRrKv5s6W&sz=w2000",
  },
  {
    id: 53,
    title: "Photography 20",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1awuARyuvPLsrbrQQ_pCvU0RxoVU-R70C&sz=w2000",
  },
  {
    id: 54,
    title: "Photography 21",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=19lg_whgIVQAxi7UiS2PORHCHibB4ga3V&sz=w2000",
  },
  {
    id: 55,
    title: "Photography 22",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1by_lW158pp_Cyl7pW0pKwslZfXFMh9NV&sz=w2000",
  },
  {
    id: 56,
    title: "Photography 23",
    tag: "photography",
    desc: "• Photography•",
    img: "https://drive.google.com/thumbnail?id=1J-yUJIPVGejQEUixnit05MJT0pv3PsuO&sz=w2000",
  },
  {
    id: 57,
    title: "One Piece 1",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=1GC8ZuY1Pg7qR3KqeiXUfWxJBd4EsCYJX&sz=w2000",
  },
  {
    id: 58,
    title: "One Piece 2",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=1zZuf9kFpk6r2p8kKLWetyULTTQBa67OB&sz=w2000",
  },
  {
    id: 59,
    title: "One Piece 3",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=1W1h_UW_6eE21a31MeFR5IZPg9QKQwsmS&sz=w2000",
  },
  {
    id: 60,
    title: "One Piece 4",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=1uLtBVCi7JSfUU7wvrpyqxN2QWexyTr0q&sz=w2000",
  },
  {
    id: 61,
    title: "One Piece 5",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=18Bpt3uezDbgH3opdRaYptefYIEo3sIQn&sz=w2000",
  },
  {
    id: 62,
    title: "One Piece 6",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=14kSabRi7XycbvUTXsIwhkZPoRaCSJiK3&sz=w2000",
  },
  {
    id: 63,
    title: "One Piece 7",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=12yNwqOqleUg3yBecmKBxkLk0BYsq3tjc&sz=w2000",
  },
  {
    id: 64,
    title: "One Piece 8",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=1IEutDqT-8vNbjUtLWgZdQ7lgRmdECuC8&sz=w2000",
  },
  {
    id: 65,
    title: "One Piece 9",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=1RfYEhuV4zfXNc75MCVv3Rc-TJ9DHkjcn&sz=w2000",
  },
  {
    id: 66,
    title: "One Piece 10",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=141rbagMhB06R33dZGgCymBGqF5KoWO7n&sz=w2000",
  },
  {
    id: 67,
    title: "One Piece 11",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    img: "https://drive.google.com/thumbnail?id=1zBUUtaGIhqUgMNzC6h1LOpt_kkOCZL4M&sz=w2000",
  },
  {
    id: 68,
    title: "One Piece 12",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    type: "video",
    video:
      "https://drive.google.com/file/d/1Nim98zmho4fe8Xrh5ZtEYi_AsFABT7jA/view?usp=drive_link",
    img: "",
  },
  {
    id: 69,
    title: "One Piece 13",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    type: "video",
    video:
      "https://drive.google.com/file/d/1bAhRNViO9MNbi5k4oQfhbbwI-cf1vZSv/view?usp=drive_link",
    img: "",
  },
  {
    id: 70,
    title: "One Piece 14",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    type: "video",
    video:
      "https://drive.google.com/file/d/13DJp12ZmLl5bddqyyl3CqHjQ146njiVt/view?usp=drive_link",
    img: "",
  },
  {
    id: 71,
    title: "One Piece 15",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    type: "video",
    video:
      "https://drive.google.com/file/d/1Na6eCWPwgpsh86yUb-Gp62-I3VcplGEL/view?usp=drive_link",
    img: "",
  },
  {
    id: 72,
    title: "One Piece 16",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    type: "video",
    video:
      "https://drive.google.com/file/d/1P3P9eEMi6T-Xa6Mw489xbsnLk_lvyxg0/view?usp=drive_link",
    img: "",
  },
  {
    id: 73,
    title: "One Piece 17",
    tag: "one_piece",
    desc: "Custom One Piece murals • printable menus • logo design • branding materials",
    type: "video",
    video:
      "https://drive.google.com/file/d/1OwGqvoLxJVmFtAAxASsJVS4yTac0Vbjt/view?usp=drive_link",
    img: "",
  },
  {
    id: 74,
    title: "Hungry Bob 1",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1yPw0PKiJCZvNjq5UiRl_qm-zF3LeHY4H&sz=w2000",
  },
  {
    id: 75,
    title: "Hungry Bob 2",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1DCa5mjwU1aQqH2E_SK3j9T6uHgfrLZBZ&sz=w2000",
  },
  {
    id: 76,
    title: "Hungry Bob 3",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1VFOUcqK-zobxZF4tgTzLQgTU5kzPIyvE&sz=w2000",
  },
  {
    id: 77,
    title: "Hungry Bob 4",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1eFx05U0S2ywNNmkogjn3-xqEDxNqsAFh&sz=w2000",
  },
  {
    id: 78,
    title: "Hungry Bob 5",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1AGcnq4ImN8prFH8sbut5UxkVe1lDckeX&sz=w2000",
  },
  {
    id: 79,
    title: "Hungry Bob 6",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1TK6qhvGRLGDwz0urlXkPMyuyjG1yVn7L&sz=w2000",
  },
  {
    id: 80,
    title: "Hungry Bob 7",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1pgWRAiicEKKuPuNSkKHfCQqSfqBF9Wll&sz=w2000",
  },
  {
    id: 81,
    title: "Hungry Bob 8",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1cSAQDhY1lPBkFshloCSD4ItZHMbG0yw5&sz=w2000",
  },
  {
    id: 82,
    title: "Hungry Bob 9",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1sx8jjDgbyb4udqrCNt8mAByQXIdVO0dC&sz=w2000",
  },
  {
    id: 83,
    title: "Hungry Bob 10",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1ntWnjUFWh0fELRRcEtvzqkcrd2TXnmBu&sz=w2000",
  },
  {
    id: 85,
    title: "Hungry Bob 12",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1LulvkgstesWCQotIVq9mdhAD7BV-6Qvz&sz=w2000",
  },
  {
    id: 86,
    title: "Hungry Bob 13",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1wxHFvSsbvkCg-b0Uyr5kw7ZEvqHePOUG&sz=w2000",
  },
  {
    id: 87,
    title: "Hungry Bob 14",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1MBnJAm4yqIodxB7ATVUh5cDnFeIHvUyA&sz=w2000",
  },
  {
    id: 88,
    title: "Hungry Bob 15",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1ccUZHf36WiwvgksmUcTzcxu5TPJvIRvO&sz=w2000",
  },
  {
    id: 89,
    title: "Hungry Bob 16",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1SCd2J4Ny9kqHxrOJtJxjwEzir-kvPlvr&sz=w2000",
  },
  {
    id: 90,
    title: "Hungry Bob 17",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1eOGGZEdMyx6srjVFU6_helCn03feoa5A&sz=w2000",
  },
  {
    id: 91,
    title: "Hungry Bob 18",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=12U8PEIOM5atYfpfipyOqfd0A3bbY-Xyy&sz=w2000",
  },
  {
    id: 92,
    title: "Hungry Bob 19",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1TmLqpmuwsod1JYxJLdxppYjAUTxWnN4N&sz=w2000",
  },
  {
    id: 93,
    title: "Hungry Bob 20",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1fFwaWf_L8MBhSMOgn9p_ML6pP1lEv1WE&sz=w2000",
  },
  {
    id: 94,
    title: "Hungry Bob 21",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1-46qj1fV3pBAg77xsYqN1S4iT-XWGNRi&sz=w2000",
  },
  {
    id: 95,
    title: "Hungry Bob 22",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=14DD7-8qXHE9BqDF7D48Wk-ikd1PAbMHs&sz=w2000",
  },
  {
    id: 96,
    title: "Hungry Bob 23",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1pMkf8sF5tCWI_RD8e6CfcZMszjpVugMc&sz=w2000",
  },
  {
    id: 97,
    title: "Hungry Bob 24",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1--wcxBWTBSLwtWSm76DrzUtBwIKq_8fL&sz=w2000",
  },
  {
    id: 98,
    title: "Hungry Bob 25",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1J6wn8mw0P_8E69VKb0vLLxkXCJR08Y8S&sz=w2000",
  },
  {
    id: 99,
    title: "Hungry Bob 26",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1c9meB6R0EMkeZJOHir5CKnZcnDGHaEDE&sz=w2000",
  },
  {
    id: 100,
    title: "Hungry Bob 27",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1iLN5fQw9ujLLVfqi0kpuMhSjDkexR-vp&sz=w2000",
  },
  {
    id: 101,
    title: "Hungry Bob 28",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1ekWDYF7Laj7T6NzG0bgi-W-bvT0YHn79&sz=w2000",
  },
  {
    id: 102,
    title: "Hungry Bob 29",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1ckE0Pd7ha0_SOxmmOoQ6Hd2AaYIj8-U7&sz=w2000",
  },
  {
    id: 103,
    title: "Hungry Bob 30",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    img: "https://drive.google.com/thumbnail?id=1HCOgQzTvuTnKvzPpGYhX_2w459r4KJ22&sz=w2000",
  },
  {
    id: 104,
    title: "Hungry Bob 31",
    tag: "hungry_bob",
    desc: "Logo • social media content • printable and display menus • promotional video • Grab & Foodpanda designs • food photography",
    type: "video",
    video:
      "https://drive.google.com/file/d/1fwk6uDWnx9E-gDhJswfOWMj6CAlBjqRG/view?usp=drive_link",
    img: "",
  },
  {
    id: 105,
    title: "Dabang Coffee 3",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1ZD0q9nbOrph9dXP-Tx5QMO2lKzXY2cTw&sz=w2000",
  },
  {
    id: 106,
    title: "Dabang Coffee 4",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1FbkQoP3I4lz1ZF0yJ4E1ZHmxLNYL7ZT7&sz=w2000",
  },
  {
    id: 107,
    title: "Dabang Coffee 5",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1woHJ1LmXPpSCK7ORq3Xwwg2Uyg5VX2aS&sz=w2000",
  },
  {
    id: 108,
    title: "Dabang Coffee 6",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=11jSB3CHq4DwMNqLgZNuqeQdV1NBjYW1g&sz=w2000",
  },
  {
    id: 109,
    title: "Dabang Coffee 7",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1Dq8Z_CdARkAn4NbnvGP80KVopDs4ZblL&sz=w2000",
  },
  {
    id: 110,
    title: "Dabang Coffee 8",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1jIh4SAuLhdgMAnMhIZbFsnx4CAhKn6tt&sz=w2000",
  },
  {
    id: 111,
    title: "Dabang Coffee 9",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1i5tZC3comNj5WRLWlsfXhNG65jrtDUta&sz=w2000",
  },
  {
    id: 112,
    title: "Dabang Coffee 10",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1BTALi54xN64QUOViEVeBLuqJ04rkaJz-&sz=w2000",
  },
  {
    id: 113,
    title: "Dabang Coffee 11",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1bhHpwrDuKZAyO7VRCwKlfPNw2BYXOjBv&sz=w2000",
  },
  {
    id: 114,
    title: "Dabang Coffee 12",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1dq8yhW2M4OyR7w0zbaiPZ0bLQePa_9bv&sz=w2000",
  },
  {
    id: 115,
    title: "Dabang Coffee 13",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1allh3fH0bumoOhFURJ3kkvZ7K1VeVmEG&sz=w2000",
  },
  {
    id: 116,
    title: "Dabang Coffee 14",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1Uae71DpytxMpiL3jijswmiVIpGdmwTJP&sz=w2000",
  },
  {
    id: 117,
    title: "Dabang Coffee 15",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1YYXdF_LXdjEqSfDd28TPMeBQTkwB0vgs&sz=w2000",
  },
  {
    id: 118,
    title: "Dabang Coffee 16",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1jfImCb6FStulctthmPMu4uxp418LH3oS&sz=w2000",
  },
  {
    id: 119,
    title: "Dabang Coffee 17",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1JhUz1__pH1PzSFMThq2PgWrRYH76B9iP&sz=w2000",
  },
  {
    id: 120,
    title: "Dabang Coffee 18",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1bA2XVhe1NwYX5CJGX5P2KIBfurljAU4m&sz=w2000",
  },
  {
    id: 121,
    title: "Dabang Coffee 19",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    img: "https://drive.google.com/thumbnail?id=1xAwWce42VGsr6AaWbZzh_uImtgQmCxYU&sz=w2000",
  },
  {
    id: 122,
    title: "Dabang Coffee 20",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    type: "video",
    video:
      "https://drive.google.com/file/d/1fjVRqWCb1QtqYqe_K3R-zuEKtSsUfbNw/view?usp=drive_link",
    img: "",
  },
  {
    id: 123,
    title: "Dabang Coffee 21",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    type: "video",
    video:
      "https://drive.google.com/file/d/1PPOyTiFH1EGzGeXDWqjSJJnChAsuTCGI/view?usp=drive_link",
    img: "",
  },
  {
    id: 124,
    title: "Dabang Coffee 22",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    type: "video",
    video:
      "https://drive.google.com/file/d/1w81v3EzH2r8kCh_0F7Os-4Zu0lZkv_TT/view?usp=drive_link",
    img: "",
  },
  {
    id: 125,
    title: "Dabang Coffee 23",
    tag: "dabang",
    desc: "Graphic design • logo • social media posts • printable and display menus • video reels • promotional video • Grab & Foodpanda materials • menu photography",
    type: "video",
    video:
      "https://drive.google.com/file/d/1XTik7KBbnxot7Cgt-p3vlcTk6JHWfWFN/view?usp=drive_link",
    img: "",
  },
  {
    id: 126,
    title: "Cookqoo 1",
    tag: "cookqoo",
    desc: "• Graphic design • Photography •",
    img: "https://drive.google.com/thumbnail?id=1nHm0_76uhMWTkl5s2DxVc5PacU6HC-BN&sz=w2000",
  },
  {
    id: 127,
    title: "Cookqoo 2",
    tag: "cookqoo",
    desc: "• Graphic design • Photography •",
    img: "https://drive.google.com/thumbnail?id=1aj2ZDwWsQg_J1C4gJespdEqoJAjhu3Fc&sz=w2000",
  },
  {
    id: 128,
    title: "Cookqoo 3",
    tag: "cookqoo",
    desc: "• Graphic design • Photography •",
    img: "https://drive.google.com/thumbnail?id=1ZfuxwnxQUn05fIgiCNWAyL_RSL8D9PVh&sz=w2000",
  },

  {
    id: 129,
    title: "Cookqoo 4",
    tag: "cookqoo",
    desc: "• Graphic design • Photography •",
    type: "video",
    video:
      "https://drive.google.com/file/d/11yZm7f2khL9PdhhwVLRzVGX0ne-iNWKP/view?usp=drive_link",
    img: "",
  },
];
